config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels
  namespace :admin do
  resources :users
  end
  resources :tasks
  root 'tasks#index'
end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  #has_and_belongs_to_many :tasks
  #belongs_to :task
  has_many :tasks_labels, dependent: :destroy
  has_many :tasks, through: :tasks_labels
  accepts_nested_attributes_for :tasks_labels, :reject_if => proc { |a| 
     a['label_id'].blank? }
  accepts_nested_attributes_for :tasks

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  def index
    @labels = Label.all
  end

  # GET /labels/1
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
    @label.user_id = current_user.id
    @label.tasks.build
    @label.tasks_labels.build
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  def create
    @label = Label.new(label_params)
    @label.user_id = current_user.id

    if @label.save
      redirect_to @label, notice: 'Label was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /labels/1
  def update
    if @label.update(label_params)
      redirect_to @label, notice: 'Label was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /labels/1
  def destroy
    @label.destroy
    redirect_to labels_url, notice: 'Label was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def label_params
      params.require(:label).permit(:title, :content, :user_id)
    end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
   
    <%= form.hidden_field :user_id %>
  </div>

  

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<nav class="nav">
  <a class="nav-link active" href="#"><strong>Everyleaf Task</strong></a>
  
</nav>
<hr class="border border-dark">
<h1 style="text-align:center;">Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<nav class="nav">
  <a class="nav-link active" href="#"><strong>Everyleaf Task</strong></a>
  
</nav>
<hr class="border border-dark">
<div class="card-body">
<h1  style="text-align:center;">Labels</h1>

<table  class="table table-striped table-dark">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      
      <th colspan="3">More Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.title %></td>
        <td><%= label.content %></td>
        <td><%= label.user.username %></td>
        
        <td><button type="button" class="btn btn-success"><%= link_to 'Show', label %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_label_path(label) %></button></td>
        <td><button type="button" class="btn btn-success"><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path, class: '' %>
</div>

app/views/labels/label.html.erb
<div class="label">
    <%= f.label_for :title %>
    <%= f.text_field :title %>
    <%= link_to_function "remove", "$(this).up('.label_association').remove()" %>
  </div>

app/views/labels/label_association.html.erb
<div class="label_association">
  <% fields_for :labels do |f| %>
    <%= f.collection_select(:label_id, Label.all,
      :id, :title, :include_blank => true) %>
    <%= link_to_function "remove", "$(this).up('.label_association').remove()" %>
  <% end %>
  </div>

app/views/labels/new.html.erb
<nav class="nav">
  <a class="nav-link active" href="#"><strong>Everyleaf Task</strong></a>
  
</nav>
<hr class="border border-dark">
<h1 style="text-align:center;">New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<nav class="nav">
  <a class="nav-link active" href="#"><strong>Everyleaf Task</strong></a>
  
</nav>
<hr class="border border-dark">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @label.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @label.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @label.user.username %>
</p>



<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>