config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels
  namespace :admin do
  resources :users
  end
  resources :tasks
  root 'tasks#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :username,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def self.admins
    @users = User.all
    @admins = 0
    @users.each do |user|
      if user.user_type == "admin"
        @admins += 1
      end
    end
    return @admins
  end
 end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :give_users_right_to_admin, only: [:index,:new,:create,:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:destroy]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  def show
    
  end
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def give_users_right_to_admin
    unless current_user && current_user.user_type == "admin"
      redirect_to root_url, notice: "only admin user can access this page"
    end
  end
  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end
  def check_admin
    @admins = 0
    User.all.each do |user|
      if user.user_type == 'admin'
        @admins += 1
      end
    end
    if @admins == 1
      redirect_to users_path, notice: 'At leat one admin must remain'
    else
      @user.destroy
      redirect_to users_url, notice: 'User has successfully destroyed'
    end
  end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_admin, only: [:destroy]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def edit
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }

      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def check_admin
    @admins = 0
    User.all.each do |user|
      if user.user_type == 'admin'
        @admins += 1
      end
    end
    if @admins == 1
      redirect_to users_path, notice: 'At leat one admin must remain'
    else
      @user.destroy
      redirect_to users_url, notice: 'User has successfully destroyed'
    end
  end
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation, :user_type)
  end
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="card" style="width: 18rem;">
<div class="card-body">
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
 <%= f.label :UserName %>
 <%= f.text_field :username,class:'form-control' %>
 <%= f.label :email %>
 <%= f.email_field :email,class:'form-control' %>
 <%= f.label :password %></br>
 <%= f.select(:user_type, options_for_select([['admin','admin'],['general user','general user']])) %></br></br>
 <%= f.password_field :password,class:'form-control' %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation,class:'form-control' %>
 <br>
 <%= f.submit "Create my account",class:'btn btn-success' %>
<% end %>
</div>
</div>

app/views/admin/users/edit.html.erb



<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<nav class="nav">
  <a class="nav-link active" href="#"><strong>Everyleaf Task</strong></a> 
</nav>
<hr class="border border-dark">
<div class="card-body">
<p id="notice"><%= notice %></p>

<h1 style="text-align:center;">Users</h1>

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">number of tasks </th>
       <th scope="col">User Type </th>  
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', admin_user_path(user), class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>
</div>

app/views/admin/users/new.html.erb
<div class="card" style="width: 18rem;">
<div class="card-body">
<h1>Sign up</h1>
<% if @user.errors.any? %>
 <div id="error_explanation">
   <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
   <ul>
   <% @user.errors.full_messages.each do |message| %>
     <li><%= message %></li>
   <% end %>
   </ul>
 </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
 <%= f.label :UserName %>
 <%= f.text_field :username,class:'form-control' %>
 <%= f.label :email %>
 <%= f.email_field :email,class:'form-control' %></br>
 <%= f.select(:user_type, options_for_select([['admin','admin'],['general user','general user']])) %></br></br>
 <%= f.label :password %>
 <%= f.password_field :password,class:'form-control' %>
 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation,class:'form-control' %>
 <br>
 <%= f.submit "Create my account",class:'btn btn-success' %>
<% end %>
</div>
</div>

app/views/admin/users/show.html.erb

<% if logged_in? %>
<h1><%= @user.username %> page's</h1>
<p>email address: <%= @user.email %></p>
</div>
<div class="content-content">
<h3><%= link_to 'View Recent tasks', tasks_path %></h3>
<% else %>
<h1>welcome <%= @user.username %>!</h1>
<p>email address: <%= @user.email %></p>
<%= link_to 'Please Log In', new_session_path %>
<% end %>
<% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
 <% end %>