config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :labels
  namespace :admin do
  resources :users
  end
  resources :tasks
  root 'tasks#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryleafTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>

  <body style="background-image: linear-gradient(to left, #1f4037, #99f2c8);">
  <% if current_user && current_user.user_type == "admin" %>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to 'Manage users',admin_users_path %></button>
  <% end %>
   
  <% if logged_in? %>
     <a class="btn btn-outline-success my-2 my-sm-0" href="#" style="padding-left:30px"><%= current_user.email %><span class="sr-only">(current)</span></a>
     
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%=link_to 'tasks', tasks_path %></button>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to "Logout", session_path(current_user.id), method: :delete %></button>
    
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to 'Labels', labels_path%></button>
      
  <% else %>

    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to "Sign up", new_user_path %></button>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to "Login", new_session_path %></button>
   
     
  <% end %>
  
  <%= yield %>
  <div class="card-footer">
    <strong> © EveryLeaf 2019 </strong>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>